#include <iostream>
#include <fstream>
#include "libtcod.hpp"
class tActor;
#include "destructible.h"
#include "attacker.h"
#include "ai.h"
#include "actor.h"
#include "map.h"
#include "engine.h"
#include "gui.h"
#include "pickable.h"
#include "container.h"
#include "..\googleProtocol\RogueLike.pb.h"