// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RogueLike.proto

#ifndef PROTOBUF_RogueLike_2eproto__INCLUDED
#define PROTOBUF_RogueLike_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace roguelike_google_protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RogueLike_2eproto();
void protobuf_AssignDesc_RogueLike_2eproto();
void protobuf_ShutdownFile_RogueLike_2eproto();

class actor;

// ===================================================================

class actor : public ::google::protobuf::Message {
 public:
  actor();
  virtual ~actor();

  actor(const actor& from);

  inline actor& operator=(const actor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const actor& default_instance();

  void Swap(actor* other);

  // implements Message ----------------------------------------------

  actor* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const actor& from);
  void MergeFrom(const actor& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 xpos = 1;
  inline bool has_xpos() const;
  inline void clear_xpos();
  static const int kXposFieldNumber = 1;
  inline ::google::protobuf::int32 xpos() const;
  inline void set_xpos(::google::protobuf::int32 value);

  // required int32 ypos = 2;
  inline bool has_ypos() const;
  inline void clear_ypos();
  static const int kYposFieldNumber = 2;
  inline ::google::protobuf::int32 ypos() const;
  inline void set_ypos(::google::protobuf::int32 value);

  // required int32 asciiCode = 3;
  inline bool has_asciicode() const;
  inline void clear_asciicode();
  static const int kAsciiCodeFieldNumber = 3;
  inline ::google::protobuf::int32 asciicode() const;
  inline void set_asciicode(::google::protobuf::int32 value);

  // required int32 color = 4;
  inline bool has_color() const;
  inline void clear_color();
  static const int kColorFieldNumber = 4;
  inline ::google::protobuf::int32 color() const;
  inline void set_color(::google::protobuf::int32 value);

  // required string name = 5;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 5;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required bool block = 6;
  inline bool has_block() const;
  inline void clear_block();
  static const int kBlockFieldNumber = 6;
  inline bool block() const;
  inline void set_block(bool value);

  // @@protoc_insertion_point(class_scope:roguelike_google_protocol.actor)
 private:
  inline void set_has_xpos();
  inline void clear_has_xpos();
  inline void set_has_ypos();
  inline void clear_has_ypos();
  inline void set_has_asciicode();
  inline void clear_has_asciicode();
  inline void set_has_color();
  inline void clear_has_color();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_block();
  inline void clear_has_block();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 xpos_;
  ::google::protobuf::int32 ypos_;
  ::google::protobuf::int32 asciicode_;
  ::google::protobuf::int32 color_;
  ::std::string* name_;
  bool block_;
  friend void  protobuf_AddDesc_RogueLike_2eproto();
  friend void protobuf_AssignDesc_RogueLike_2eproto();
  friend void protobuf_ShutdownFile_RogueLike_2eproto();

  void InitAsDefaultInstance();
  static actor* default_instance_;
};
// ===================================================================


// ===================================================================

// actor

// required int32 xpos = 1;
inline bool actor::has_xpos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void actor::set_has_xpos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void actor::clear_has_xpos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void actor::clear_xpos() {
  xpos_ = 0;
  clear_has_xpos();
}
inline ::google::protobuf::int32 actor::xpos() const {
  // @@protoc_insertion_point(field_get:roguelike_google_protocol.actor.xpos)
  return xpos_;
}
inline void actor::set_xpos(::google::protobuf::int32 value) {
  set_has_xpos();
  xpos_ = value;
  // @@protoc_insertion_point(field_set:roguelike_google_protocol.actor.xpos)
}

// required int32 ypos = 2;
inline bool actor::has_ypos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void actor::set_has_ypos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void actor::clear_has_ypos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void actor::clear_ypos() {
  ypos_ = 0;
  clear_has_ypos();
}
inline ::google::protobuf::int32 actor::ypos() const {
  // @@protoc_insertion_point(field_get:roguelike_google_protocol.actor.ypos)
  return ypos_;
}
inline void actor::set_ypos(::google::protobuf::int32 value) {
  set_has_ypos();
  ypos_ = value;
  // @@protoc_insertion_point(field_set:roguelike_google_protocol.actor.ypos)
}

// required int32 asciiCode = 3;
inline bool actor::has_asciicode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void actor::set_has_asciicode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void actor::clear_has_asciicode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void actor::clear_asciicode() {
  asciicode_ = 0;
  clear_has_asciicode();
}
inline ::google::protobuf::int32 actor::asciicode() const {
  // @@protoc_insertion_point(field_get:roguelike_google_protocol.actor.asciiCode)
  return asciicode_;
}
inline void actor::set_asciicode(::google::protobuf::int32 value) {
  set_has_asciicode();
  asciicode_ = value;
  // @@protoc_insertion_point(field_set:roguelike_google_protocol.actor.asciiCode)
}

// required int32 color = 4;
inline bool actor::has_color() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void actor::set_has_color() {
  _has_bits_[0] |= 0x00000008u;
}
inline void actor::clear_has_color() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void actor::clear_color() {
  color_ = 0;
  clear_has_color();
}
inline ::google::protobuf::int32 actor::color() const {
  // @@protoc_insertion_point(field_get:roguelike_google_protocol.actor.color)
  return color_;
}
inline void actor::set_color(::google::protobuf::int32 value) {
  set_has_color();
  color_ = value;
  // @@protoc_insertion_point(field_set:roguelike_google_protocol.actor.color)
}

// required string name = 5;
inline bool actor::has_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void actor::set_has_name() {
  _has_bits_[0] |= 0x00000010u;
}
inline void actor::clear_has_name() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void actor::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& actor::name() const {
  // @@protoc_insertion_point(field_get:roguelike_google_protocol.actor.name)
  return *name_;
}
inline void actor::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:roguelike_google_protocol.actor.name)
}
inline void actor::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:roguelike_google_protocol.actor.name)
}
inline void actor::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:roguelike_google_protocol.actor.name)
}
inline ::std::string* actor::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:roguelike_google_protocol.actor.name)
  return name_;
}
inline ::std::string* actor::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void actor::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:roguelike_google_protocol.actor.name)
}

// required bool block = 6;
inline bool actor::has_block() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void actor::set_has_block() {
  _has_bits_[0] |= 0x00000020u;
}
inline void actor::clear_has_block() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void actor::clear_block() {
  block_ = false;
  clear_has_block();
}
inline bool actor::block() const {
  // @@protoc_insertion_point(field_get:roguelike_google_protocol.actor.block)
  return block_;
}
inline void actor::set_block(bool value) {
  set_has_block();
  block_ = value;
  // @@protoc_insertion_point(field_set:roguelike_google_protocol.actor.block)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace roguelike_google_protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RogueLike_2eproto__INCLUDED
